import { DurableObject } from "cloudflare:workers";
import { GameEngine, type GameSnapshot } from "@monopoly/game-engine";
import type { GuestSession, RoomPlayer } from "@monopoly/shared-types";
import { isAllowedOrigin, parseWireMessage } from "./security";

interface Env { GAME_HUB: DurableObjectNamespace<GameHub>; ALLOWED_ORIGIN: string; }
type Room = { roomCode: string; hostPlayerId: string; players: RoomPlayer[]; snapshot: GameSnapshot | null; lastEmptyAt: number | null; disconnectedAt: Record<string, number>; turnDeadline?: number | null; turnTimeoutSeconds?: number | null };
type Identity = { roomCode: string; playerId: string };
const json = (status: number, body: unknown, origin: string) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json", "access-control-allow-origin": origin } });
const clean = (name: string) => name.trim().slice(0, 32);
const roomCode = () => crypto.randomUUID().replaceAll("-", "").slice(0, 6).toUpperCase();
const ROOM_CREATIONS_PER_WINDOW = 5;
const ROOM_CREATION_WINDOW_MS = 60_000;
const MAX_ROOMS = 500;

export class GameHub extends DurableObject<Env> {
  private rooms = new Map<string, Room>();
  private sockets = new Map<WebSocket, Identity>();
  private roomCreations = new Map<string, number[]>();
  constructor(ctx: DurableObjectState, env: Env) { super(ctx, env); this.ctx.blockConcurrencyWhile(async () => { const rooms = await this.ctx.storage.get<Room[]>("rooms"); this.rooms = new Map((rooms ?? []).map((room) => [room.roomCode, room])); }); }
  async fetch(request: Request): Promise<Response> {
    const requestOrigin = request.headers.get("origin");
    if (requestOrigin && !isAllowedOrigin(requestOrigin, this.env.ALLOWED_ORIGIN)) return json(403, { error: "Origin not allowed" }, this.env.ALLOWED_ORIGIN);
    const origin = requestOrigin ?? this.env.ALLOWED_ORIGIN;
    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: { "access-control-allow-origin": origin, "access-control-allow-methods": "GET,POST,OPTIONS", "access-control-allow-headers": "content-type" } });
    const url = new URL(request.url);
    if (url.pathname === "/health") return json(200, { ok: true }, origin);
    if (url.pathname === "/ws") return this.upgrade(request);
    if (request.method === "POST" && url.pathname === "/rooms") {
      if (this.rooms.size >= MAX_ROOMS) return json(503, { error: "The server is at capacity, try again shortly" }, origin);
      if (!this.allowRoomCreation(request.headers.get("cf-connecting-ip") ?? "unknown")) return json(429, { error: "Too many rooms created, try again in a minute" }, origin);
      return this.create(request, origin);
    }
    const join = url.pathname.match(/^\/rooms\/([^/]+)\/join$/); if (request.method === "POST" && join) return this.join(request, join[1], origin);
    return json(404, { error: "Not found" }, origin);
  }
  /** Rooms are persisted to Durable Object storage, so unbounded creation fills it. */
  private allowRoomCreation(client: string, now = Date.now()): boolean {
    const recent = (this.roomCreations.get(client) ?? []).filter((at) => now - at < ROOM_CREATION_WINDOW_MS);
    this.roomCreations.set(client, recent);
    if (recent.length >= ROOM_CREATIONS_PER_WINDOW) return false;
    recent.push(now);
    return true;
  }
  private async create(request: Request, origin: string) { const body = await request.json<{ name?: unknown }>().catch(() => ({})); const name = typeof body.name === "string" ? clean(body.name) : ""; if (!name) return json(400, { error: "Name is required" }, origin); let code = roomCode(); while (this.rooms.has(code)) code = roomCode(); const playerId = crypto.randomUUID(), sessionToken = crypto.randomUUID(); const engine = new GameEngine(6); engine.connect(playerId, name); this.rooms.set(code, { roomCode: code, hostPlayerId: playerId, players: [{ playerId, name, sessionToken, connected: false }], snapshot: engine.snapshot(), lastEmptyAt: Date.now(), disconnectedAt: {}, turnDeadline: null, turnTimeoutSeconds: null }); await this.persist(); return json(201, { roomCode: code, playerId, sessionToken }, origin); }
  private async join(request: Request, codeValue: string, origin: string) { const room = this.rooms.get(codeValue.toUpperCase()); const body = await request.json<{ name?: unknown }>().catch(() => ({})); const name = typeof body.name === "string" ? clean(body.name) : ""; if (!room) return json(404, { error: "Room not found" }, origin); if (!name) return json(400, { error: "Name is required" }, origin); if (room.snapshot?.gameStarted || room.players.length >= 6) return json(409, { error: room.snapshot?.gameStarted ? "Game already started" : "Room is full" }, origin); if (room.players.some((player) => player.name.toLowerCase() === name.toLowerCase())) return json(409, { error: "Name is already in use" }, origin); const playerId = crypto.randomUUID(), sessionToken = crypto.randomUUID(); const engine = room.snapshot ? GameEngine.fromSnapshot(room.snapshot) : new GameEngine(6); if (!room.snapshot) for (const player of room.players) engine.connect(player.playerId, player.name); if (!engine.connect(playerId, name)) return json(409, { error: "Unable to join game lobby" }, origin); room.snapshot = engine.snapshot(); room.players.push({ playerId, name, sessionToken, connected: false }); await this.persist(); return json(200, { roomCode: room.roomCode, playerId, sessionToken }, origin); }
  private upgrade(request: Request) { if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") return json(426, { error: "Expected WebSocket" }, this.env.ALLOWED_ORIGIN); const pair = new WebSocketPair(); const [client, server] = Object.values(pair); this.ctx.acceptWebSocket(server); return new Response(null, { status: 101, webSocket: client }); }
  async webSocketMessage(socket: WebSocket, raw: string | ArrayBuffer) { const message = parseWireMessage(raw); if (!message) return this.error(socket, "BAD_REQUEST", "Malformed message"); if (message.event === "room:join") return this.socketJoin(socket, message.payload); const identity = this.sockets.get(socket) ?? socket.deserializeAttachment() as Identity | null; if (!identity) return this.error(socket, "NOT_JOINED", "Join a room first"); const room = this.rooms.get(identity.roomCode); if (!room) return this.error(socket, "ROOM_NOT_FOUND", "Room not found"); if (message.event === "state:sync_request") return this.emitState(socket, room); if (message.event === "game:action") return this.action(socket, room, identity.playerId, message.payload); if (message.event === "message" && typeof message.payload === "string") return this.broadcast(room.roomCode, "game:message", { from: room.players.find((player) => player.playerId === identity.playerId)?.name, message: message.payload.slice(0, 500) }); return this.error(socket, "BAD_EVENT", "Unsupported event"); }
  private async socketJoin(socket: WebSocket, payload: unknown) { const value = payload as Partial<GuestSession>; const room = typeof value?.roomCode === "string" ? this.rooms.get(value.roomCode.toUpperCase()) : undefined; const player = room?.players.find((candidate) => candidate.playerId === value.playerId && candidate.sessionToken === value.sessionToken); if (!room || !player) return this.error(socket, "AUTH_FAILED", "Invalid room session"); room.disconnectedAt ??= {}; delete room.disconnectedAt[player.playerId]; player.connected = true; if (room.snapshot) { const wasPaused = room.snapshot.pausedPlayerId === player.playerId; const engine = GameEngine.fromSnapshot(room.snapshot); engine.resumePlayer(player.playerId); room.snapshot = engine.snapshot(); this.updateTurnDeadline(room, wasPaused); } room.lastEmptyAt = null; const identity = { roomCode: room.roomCode, playerId: player.playerId }; this.sockets.set(socket, identity); socket.serializeAttachment(identity); await this.persist(); this.emitState(socket, room); this.broadcastRoom(room); }
  private async action(socket: WebSocket, room: Room, playerId: string, action: unknown) { let engine: GameEngine; if (room.snapshot) engine = GameEngine.fromSnapshot(room.snapshot); else { engine = new GameEngine(6); for (const player of room.players) engine.connect(player.playerId, player.name); } const beforeRevision = engine.snapshot().turnRevision; const events: Array<{ type: string; reason?: string }> = []; engine.on((event) => events.push(event)); if (!engine.handle(playerId, action)) return this.error(socket, "REJECTED", events.find((event) => event.type === "rejected")?.reason ?? "Action rejected"); room.snapshot = engine.snapshot(); this.updateTurnDeadline(room, room.snapshot.turnRevision !== beforeRevision); await this.persist(); for (const event of events) if (event.type !== "state" && event.type !== "rejected") this.broadcast(room.roomCode, `game:${event.type}`, event); this.broadcastRoom(room); }
  private emitState(socket: WebSocket, room: Room) { this.emit(socket, "room:state", { roomCode: room.roomCode, hostPlayerId: room.hostPlayerId, locked: room.snapshot?.gameStarted ?? false, turnDeadline: room.turnDeadline ?? null, players: room.players.map(({ playerId, name, connected }) => ({ playerId, name, connected })) }); if (room.snapshot) this.emit(socket, "game:state", room.snapshot); }
  private broadcastRoom(room: Room) { for (const socket of this.ctx.getWebSockets()) { const identity = socket.deserializeAttachment() as Identity | null; if (identity?.roomCode === room.roomCode) this.emitState(socket, room); } }
  private broadcast(roomCodeValue: string, event: string, payload: unknown) { for (const socket of this.ctx.getWebSockets()) if ((socket.deserializeAttachment() as Identity | null)?.roomCode === roomCodeValue) this.emit(socket, event, payload); }
  private emit(socket: WebSocket, event: string, payload?: unknown) { if (socket.readyState === 1) socket.send(JSON.stringify({ event, payload })); }
  private error(socket: WebSocket, code: string, message: string) { this.emit(socket, "game:error", { code, message }); }
  async webSocketClose(socket: WebSocket) { const identity = this.sockets.get(socket) ?? socket.deserializeAttachment() as Identity | null; if (!identity) return; this.sockets.delete(socket); const hasAnotherConnection = this.ctx.getWebSockets().some((candidate) => candidate !== socket && (candidate.deserializeAttachment() as Identity | null)?.roomCode === identity.roomCode && (candidate.deserializeAttachment() as Identity | null)?.playerId === identity.playerId); if (hasAnotherConnection) return; const room = this.rooms.get(identity.roomCode), player = room?.players.find((candidate) => candidate.playerId === identity.playerId); if (room && player) { room.disconnectedAt ??= {}; player.connected = false; room.disconnectedAt[player.playerId] = Date.now(); if (room.snapshot) { const engine = GameEngine.fromSnapshot(room.snapshot); engine.pauseForReconnect(player.playerId); room.snapshot = engine.snapshot(); this.updateTurnDeadline(room, false); } room.lastEmptyAt = room.players.some((candidate) => candidate.connected) ? null : Date.now(); await this.persist(); this.broadcastRoom(room); } }
  async alarm() { const now = Date.now(); for (const room of this.rooms.values()) { if (room.turnDeadline && room.turnDeadline <= now && room.snapshot) { const engine = GameEngine.fromSnapshot(room.snapshot); room.turnDeadline = null; if (engine.expireTurn()) { room.snapshot = engine.snapshot(); this.updateTurnDeadline(room, true); this.broadcastRoom(room); } } room.disconnectedAt ??= {}; for (const [playerId, disconnectedAt] of Object.entries(room.disconnectedAt)) if (now - disconnectedAt >= 30000) { delete room.disconnectedAt[playerId]; room.players = room.players.filter((player) => player.playerId !== playerId); if (room.snapshot) { const engine = GameEngine.fromSnapshot(room.snapshot); engine.disconnect(playerId); room.snapshot = engine.snapshot(); room.hostPlayerId = room.snapshot.lobbyHostId ?? room.players[0]?.playerId ?? ""; this.updateTurnDeadline(room, true); } this.broadcastRoom(room); } if (room.lastEmptyAt && !room.players.some((player) => player.connected) && now - room.lastEmptyAt >= 600000) this.rooms.delete(room.roomCode); } await this.persist(); }
  private updateTurnDeadline(room: Room, reset: boolean) { const snapshot = room.snapshot; const seconds = snapshot?.turnTimeoutSeconds; if (!snapshot || !seconds || !snapshot.gameStarted || snapshot.phase === "finished" || snapshot.pausedPlayerId) { room.turnDeadline = null; room.turnTimeoutSeconds = null; return; } if (reset || !room.turnDeadline || room.turnTimeoutSeconds !== seconds) { room.turnDeadline = Date.now() + seconds * 1000; room.turnTimeoutSeconds = seconds; } }
  private async persist() { await this.ctx.storage.put("rooms", [...this.rooms.values()]); const deadlines = [...this.rooms.values()].map((room) => room.turnDeadline).filter((deadline): deadline is number => typeof deadline === "number" && deadline > Date.now()); await this.ctx.storage.setAlarm(Math.min(Date.now() + 30000, ...deadlines)); }
}
export default { fetch(request: Request, env: Env) { return env.GAME_HUB.get(env.GAME_HUB.idFromName("global")).fetch(request); } };
